/*
 * generated by Xtext
 */
package de.nittka.tooling.jtag.ui.contentassist

import de.nittka.tooling.jtag.ui.contentassist.AbstractJtagProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class JtagProposalProvider extends AbstractJtagProposalProvider {
}
