/*
* generated by Xtext
*/
package de.nittka.tooling.jtag.ui.outline

import de.nittka.tooling.jtag.jtag.File
import org.eclipse.xtext.ui.editor.outline.IOutlineNode
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
class JtagOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
	def dispatch isLeaf(File file){
		true;
	}
}
