/*******************************************************************************
 * Copyright (C) 2017-2020 Alexander Nittka (alex@nittka.de)
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 ******************************************************************************/
/*
 * generated by Xtext
 */
package de.nittka.tooling.jtag.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.resource.ILocationInFileProvider;
import org.eclipse.xtext.ui.editor.XtextEditor;
import org.eclipse.xtext.ui.editor.findrefs.FindReferencesHandler;
import org.eclipse.xtext.ui.editor.hover.html.DefaultEObjectHoverProvider;
import org.eclipse.xtext.ui.editor.hover.html.IEObjectHoverDocumentationProvider;
import org.eclipse.xtext.ui.editor.hyperlinking.IHyperlinkHelper;
import org.eclipse.xtext.ui.editor.syntaxcoloring.IHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import de.nittka.tooling.jtag.ui.highlighting.JtagHighlightingConfiguration;
import de.nittka.tooling.jtag.ui.highlighting.JtagSemanticHighlighter;
import de.nittka.tooling.jtag.ui.hover.JTagEObjectHover;
import de.nittka.tooling.jtag.ui.hover.JtagHoverProvider;
import de.nittka.tooling.jtag.ui.linking.JtagFindReferencesHandler;
import de.nittka.tooling.jtag.ui.linking.JtagHyperlinkHelper;
import de.nittka.tooling.jtag.ui.linking.JtagLocationInFileProvider;
import de.nittka.tooling.jtag.ui.validation.JtagUIValidator;
import de.nittka.tooling.jtag.validation.JtagValidator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JtagUiModule extends de.nittka.tooling.jtag.ui.AbstractJtagUiModule {
	public JtagUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}


	@Override
	public com.google.inject.Provider<org.eclipse.xtext.resource.containers.IAllContainersState> provideIAllContainersState() {
		return org.eclipse.xtext.ui.shared.Access.getWorkspaceProjectsState();
	}

	// contributed by org.eclipse.xtext.generator.validation.ValidatorFragment
	@org.eclipse.xtext.service.SingletonBinding(eager=true)
	public Class<? extends JtagValidator> bindXarchiveValidator() {
		return JtagUIValidator.class;
	}

	public Class<? extends ILocationInFileProvider> bindXarchiveLocationInFileProvider(){
		return JtagLocationInFileProvider.class;
	}

	public Class<? extends IHyperlinkHelper> bindXarchiveHyperlinkHelper(){
		return JtagHyperlinkHelper.class;
	}

//	public Class<? extends IFoldingRegionProvider> bindXarchiveFoldingRegionProvider(){
//		return XarchiveFoldingRegionProvider.class;
//	}
//
	public Class<? extends XtextEditor> bindXarchiveXtextEditor(){
		return JtagXtextEditor.class;
	}

	public Class<? extends FindReferencesHandler> bindXarchiveReferenceFinder(){
		return JtagFindReferencesHandler.class;
	}

	public Class<? extends DefaultEObjectHoverProvider> bindEHoverProvider(){
		return JtagHoverProvider.class;
	}

	public Class<? extends IEObjectHoverDocumentationProvider> bindEObjectHover(){
		return JTagEObjectHover.class;
	}

	public Class<? extends ISemanticHighlightingCalculator> bindHighlighter(){
		return JtagSemanticHighlighter.class;
	}

	public Class<? extends IHighlightingConfiguration> bindHighlightingConfig(){
		return JtagHighlightingConfiguration.class;
	}

//	public Class<? extends XtextTemplateContextType> bindTemplateContextType() {
//		return XarchiveTemplateContextType.class;
//}
}
