/*
* generated by Xtext
*/
package de.nittka.tooling.jtag;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class JtagStandaloneSetup extends JtagStandaloneSetupGenerated{

	public static void doSetup() {
		new JtagStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

