/*******************************************************************************
 * Copyright (C) 2017-2020 Alexander Nittka (alex@nittka.de)
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 ******************************************************************************/
/*
 * generated by Xtext
 */
package de.nittka.tooling.jtag;

import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;

import de.nittka.tooling.jtag.index.JtagResourceDescriptionStrategy;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JtagRuntimeModule extends de.nittka.tooling.jtag.AbstractJtagRuntimeModule {

	public Class<? extends IDefaultResourceDescriptionStrategy> bindResourceDescriptionStrategy() {
		return JtagResourceDescriptionStrategy.class;
	}

}
