/*
 * generated by Xtext
 */
package de.nittka.tooling.jtag;

import org.eclipse.xtext.resource.IDefaultResourceDescriptionStrategy;

import de.nittka.tooling.jtag.index.JtagResourceDescriptionStrategy;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JtagRuntimeModule extends de.nittka.tooling.jtag.AbstractJtagRuntimeModule {

	public Class<? extends IDefaultResourceDescriptionStrategy> bindResourceDescriptionStrategy() {
		return JtagResourceDescriptionStrategy.class;
	}

}
